config/routes.rb
Rails.application.routes.draw do

  resources :users, :pokemons, :sessions, :application, :user_pokemons, :gyms, :battles, :trade_requests

  root to: 'application#index'
  get '/login', to: 'sessions#new'
  get '/users/:id/pokemons/new', to: 'user_pokemons#new', as: 'new_pokemons'
  get '/users/:id/pokemons/:pokemon_id/edit', to: 'user_pokemons#edit', as: 'edit_pokemons'
  patch '/users/:id/pokemons/:pokemon_id', to: 'user_pokemons#update', as: 'update_pokemons'
  get '/users/:id/pokemons/:pokemon_id/show', to: 'user_pokemons#show'
  get '/users/:id/battle/:pokemon_id', to: 'battles#new', as: 'battle_new'
  post '/users/:id/:our_pokemon_id/battle/:their_pokemon_id', to: 'battles#create', as: 'battle_create'
  get '/users/:id/trade/:pokemon_id', to: 'trade_requests#new', as: 'trade_new'
  post '/users/:id/:give_id/trade/:take_id', to: 'trade_requests#create', as: 'trade_requests_create'
  get '/users/:id/accept_trade/:trade_request_id', to: 'trade_requests#accept', as: 'trade_request_accept'
  post '/users/:id/decline_trade/:trade_request_id', to: 'trade_requests#decline', as: 'trade_request_decline'
  post '/users/:id', to: 'users#destroy', as: 'delete_user'
  get '/users/:id/trade_requests', to: 'trade_requests#user', as: 'user_trade_requests'
  post '/logout', to: 'sessions#destroy', as: 'logout'
#  get '/users/:id/trade_requests/:pokemon_id'


  # get '/users/:id/pokemons', to: 'users#pokemons'
  # get '/users/:id/pokemons/:pokemon_id', to: 'user_pokemons#show'
  # post '/users/:id/pokemons/:pokemon_id', to: 'user_pokemons#create'
end

app/models/user_pokemon.rb
class UserPokemon < ApplicationRecord
  attr_accessor :skip_password_validation
  belongs_to :user
  belongs_to :pokemon
  has_many :battles, foreign_key: 'friend_id'
  has_many :battles, foreign_key: 'foe_id'
  has_many :trade_requests, foreign_key: 'give_id'
  has_many :trade_requests, foreign_key: 'take_id'
  validates_presence_of :user, :pokemon

  def self.most_battles
    id = self.joins(:battles).group('user_pokemons.id').count.max_by {|k, v| v}.first
    self.find(id).nickname
 end

end

app/controllers/user_pokemons_controller.rb
class UserPokemonsController < ApplicationController
  def new
    @pokemons = Pokemon.all.where('starting_level < 16')
  end

  def index
    @user_pokemons = UserPokemon.all
  end

  def edit
    set_pokemon
  end

  def show
    # set_pokemon
  end

  def update
    set_pokemon
    @user_pokemon.nickname = user_pokemon_params[:nickname]
    @user_pokemon.save
    redirect_to user_path(session[:user_id])
  end

  def create
    params["pokemon"]["name"].each do |pokemon_name|
      pokemon = Pokemon.find_by(name: pokemon_name)
      UserPokemon.create(user_id: session[:user_id], pokemon: pokemon, nickname: pokemon.name, level: pokemon.starting_level)
    end
    redirect_to user_path(session[:user_id])
  end

  def destroy
    user_pokemon = UserPokemon.find(params[:id])
    user_pokemon.destroy
    redirect_to user_path(session[:user_id])
  end

  private
  def user_pokemon_params
    params.require(:user_pokemon).permit(:nickname)
  end

  def set_pokemon
    @user_pokemon = UserPokemon.find(params[:pokemon_id])
  end

end

app/views/user_pokemons/_user_pokemon_profile.html.erb
<div>
  <img src="https://img.pokemondb.net/artwork/<%= Pokemon.find(user.pokemon_id) %>.jpg" alt="" />
  <p><%= user_pokemon.nickname %></p>
  <label>Level:</label>
  <p><%= user_pokemon.level %></p>
  <label>Element:</label>
  <p><%= user_pokemon.element.name %></p>
</div>

app/views/user_pokemons/index.html.erb
<%= form_for @user_pokemon do %>
  <% @pokemons.each do |pokemon| %>
    <label for=""><%= pokemon.name %></label>
    <input type="checkbox" name="pokemon[name][]" value="<%= pokemon.name %>">
  <% end %>
<%= submit_tag 'Submit' %>

app/views/user_pokemons/new.html.erb
<%= form_tag user_pokemons_path, method: :post %>
  <% @pokemons.each do |pokemon| %>
    <label for=""><%= pokemon.name %></label>
    <input type="checkbox" name="pokemon[name][]" value="<%= pokemon.name %>">
  <% end %>
<%= submit_tag 'Submit' %>