config/routes.rb
Rails.application.routes.draw do

  resources :users, :pokemons, :sessions, :application, :user_pokemons, :gyms, :battles, :trade_requests

  root to: 'application#index'
  get '/login', to: 'sessions#new'
  get '/users/:id/pokemons/new', to: 'user_pokemons#new', as: 'new_pokemons'
  get '/users/:id/pokemons/:pokemon_id/edit', to: 'user_pokemons#edit', as: 'edit_pokemons'
  patch '/users/:id/pokemons/:pokemon_id', to: 'user_pokemons#update', as: 'update_pokemons'
  get '/users/:id/pokemons/:pokemon_id/show', to: 'user_pokemons#show'
  get '/users/:id/battle/:pokemon_id', to: 'battles#new', as: 'battle_new'
  post '/users/:id/:our_pokemon_id/battle/:their_pokemon_id', to: 'battles#create', as: 'battle_create'
  get '/users/:id/trade/:pokemon_id', to: 'trade_requests#new', as: 'trade_new'
  post '/users/:id/:give_id/trade/:take_id', to: 'trade_requests#create', as: 'trade_requests_create'
  get '/users/:id/accept_trade/:trade_request_id', to: 'trade_requests#accept', as: 'trade_request_accept'
  post '/users/:id/decline_trade/:trade_request_id', to: 'trade_requests#decline', as: 'trade_request_decline'
  post '/users/:id', to: 'users#destroy', as: 'delete_user'
  get '/users/:id/trade_requests', to: 'trade_requests#user', as: 'user_trade_requests'
  post '/logout', to: 'sessions#destroy', as: 'logout'
#  get '/users/:id/trade_requests/:pokemon_id'


  # get '/users/:id/pokemons', to: 'users#pokemons'
  # get '/users/:id/pokemons/:pokemon_id', to: 'user_pokemons#show'
  # post '/users/:id/pokemons/:pokemon_id', to: 'user_pokemons#create'
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :skip_password_validation
  belongs_to :gym, optional: true
  has_one :trainer
  has_one :leader
  has_many :user_pokemons
  has_many :badge_trainers
  has_many :badges, through: :badge_trainers
  has_secure_password
  validates_presence_of :name, :password

  # these methods are useful, but it makes me think that the class user knows too much
  # then again it's just answering questions about itself, nothing actually changes data
  def trade_requests_as_sender
    TradeRequest.joins(give: :user).where('user_id = ?', self.id)
  end

  def sender?
    trade_requests_as_sender.present?
  end

  def trade_requests_as_recipient
    TradeRequest.joins(take: :user).where('user_id = ?', self.id)
  end

  def recipient?
    trade_requests_as_recipient.present?
  end

  def pending_trade_requests
    sender? || recipient?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def index
    @users = User.all
  end
  def show
    set_user
  end
  def edit
    set_user
  end
  def create
    @user = User.create(user_params)
    Trainer.create(user_id: @user.id)
    login(@user)
    redirect_to user_path(@user)
  end
  def update
    set_user
    @user.update(user_params)
    redirect_to user_path(@user)
  end
  def destroy
    set_user
    @user.destroy
    redirect_to '/gyms/1'
  end
  private
    def set_user
      @user = User.find(params[:id])
    end
    def user_params
      params.require(:user).permit(:name, :age, :catchphrase, :rank, :password, :gym_id)
    end
end

app/views/users/_user_profile.html.erb
<div class="profile-">
  <img src="/assets/avatar.jpg" /><br>
  <%= link_to user.name, user_path(user) %><br>
  <% if user.catchphrase.present? %>
  <i>"<%=user.catchphrase%>"</i><br>
  <%end%>
  <label>Gym:</label>
  <%=link_to "#{user.gym.name}", gym_path(user.gym)%><br>
  <% if user.leader %>
    Leader of <%=user.gym.name%><br>
  <% elsif user.trainer %>

    <label>Rank:</label>
    <%= user.trainer.rank %><br>
    <ul><label>Badges:</label>
    <% user.trainer.badges.each do |badge| %>
    <li><%= badge.name %> Badge</li>
    <% end %></ul>
  <% end %>
</div>

app/views/users/_user_sidebar_info.erb
  <div class="side-nav-bar">
    <img class="pulse" src="/assets/avatar.jpg" />
    <h1><%= user.name %></h1>
    <% if user.trainer %>
    <h3>Level: <%= user.trainer.rank %></h3>
    <% else %>
    <h3>Leader of <%= user.gym.name %> Gym</h3>
    <% end %>
    <a href="<%= user_path(user) %>">Profile</a><br>
    <a href="<%= new_pokemons_path(user) %>">Add Pokemon</a><br>
    <a href="<%=gym_path(user.gym.id)%>">Gym</a><br>
    <a href="<%= users_path %>">Battle</a><br>
    <a href="<%= users_path %>">Trade</a><br>
    <%= link_to 'Log Out', logout_path, method: 'post'%></a>
  </div>



<!-- <div class="navbar navbar-inverse navbar-fixed-left">
  <a class="navbar-brand" href="#">Brand</a>
  <ul class="nav navbar-nav">
   <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
     <ul class="dropdown-menu" role="menu">
      <li><a href="#">Sub Menu1</a></li>
      <li><a href="#">Sub Menu2</a></li>
      <li><a href="#">Sub Menu3</a></li>
      <li class="divider"></li>
      <li><a href="#">Sub Menu4</a></li>
      <li><a href="#">Sub Menu5</a></li>
     </ul>
   </li>
   <li><a href="#">Link2</a></li>
   <li><a href="#">Link3</a></li>
   <li><a href="#">Link4</a></li>
   <li><a href="#">Link5</a></li>
  </ul>
</div>
<div class="container">
 <div class="row">
   <h2>Left side Navigation bar (Fixed)</h2>

   <p>Left side Navigation</p>
 </div>
</div> -->

app/views/users/edit.html.erb
<h1>Edit Trainer</h1>
<%=form_for @user do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :gym %> #to add dropdown
    <%= f.text_field :gym %>
  </p>

  <p>
    <%= f.label :age %>
    <%= f.text_field :age %>
  </p>

  <p>
    <%=f.label :catchphrase %>
    <%= f.text_field :catchphrase %>
  </p>
  <%= f.submit "Edit" %>
<% end %>
<%= button_to('Delete', user_path(@user), {method: 'delete'}) %>

app/views/users/index.html.erb
<%= render partial: "user_profile", collection: @users, as: :user %>

app/views/users/new.html.erb
<h1>Trainer Registration</h1>
<%=form_for @user do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :gym %>
    <%= f.collection_select(:gym_id, Gym.all, :id, :name)%>
  </p>

  <p>
    <%= f.label :age %>
    <%= f.text_field :age %>
  </p>

  <p>
    <%=f.label :catchphrase %>
    <%= f.text_field :catchphrase %>
  </p>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<div class="pokemon_profile">
<%= render partial: "user_profile", object: @user, as: :user %>
  <!-- <%= render partial: "user_pokemons/user_pokemon_profile", collection: @user_pokemons, as: :user_pokemon %> -->
  <!-- <%= render partial: "user_links" %> -->
</div>

<p><%=flash[:message]%></p>
<div>
  <% if session[:user_id] == @user.id %>
    <h2><%= label_tag "pokemon", "Your Pokemon" %></h2>
    <p><%= link_to "Add New Pokemon", new_pokemons_path(session[:user_id]) %></p>
  <% else %>
    <h2><%= label_tag "pokemon", "#{@user.name}'s Pokemon" %></h2>
  <% end %>
  <br><% @user.user_pokemons.each do |pokemon| %>
    <div class="align">
      <div class="crop"><img src="https://img.pokemondb.net/artwork/<%= Pokemon.find(pokemon.pokemon_id).name.downcase %>.jpg" alt="" /></div >
      <p><strong><%= pokemon.nickname %></strong> Level <%= pokemon.level %></p>
      <p>Type: <%= Pokemon.find(pokemon.pokemon_id).element.name %></p>
      <% if session[:user_id] != @user.id %>
        <%= link_to "Battle", battle_new_path(session[:user_id], pokemon) %>
        <%= link_to "Initiate Trade", trade_new_path(session[:user_id], pokemon) %>
      <% else %>
        <%= link_to "Edit Nickname", edit_pokemons_path(session[:user_id], pokemon) %>
        <%= link_to "Release", user_pokemon_path(pokemon), method: :delete %>
      <% end %>
    </div>
  <% end %>
  <% if current_user_can_kick_out(@user) %>
    <%= link_to "Kick out", user_path(@user), method: :delete%>
  <% end %></br>
</div>
<% if @user.pending_trade_requests && @user == current_user %>
  <div class = "trade_request"><%= link_to 'You have pending trade requests!', user_trade_requests_path(session[:user_id]) %></div>
<% end %>