config/routes.rb
Rails.application.routes.draw do

  resources :users, :pokemons, :sessions, :application, :user_pokemons, :gyms, :battles, :trade_requests

  root to: 'application#index'
  get '/login', to: 'sessions#new'
  get '/users/:id/pokemons/new', to: 'user_pokemons#new', as: 'new_pokemons'
  get '/users/:id/pokemons/:pokemon_id/edit', to: 'user_pokemons#edit', as: 'edit_pokemons'
  patch '/users/:id/pokemons/:pokemon_id', to: 'user_pokemons#update', as: 'update_pokemons'
  get '/users/:id/pokemons/:pokemon_id/show', to: 'user_pokemons#show'
  get '/users/:id/battle/:pokemon_id', to: 'battles#new', as: 'battle_new'
  post '/users/:id/:our_pokemon_id/battle/:their_pokemon_id', to: 'battles#create', as: 'battle_create'
  get '/users/:id/trade/:pokemon_id', to: 'trade_requests#new', as: 'trade_new'
  post '/users/:id/:give_id/trade/:take_id', to: 'trade_requests#create', as: 'trade_requests_create'
  get '/users/:id/accept_trade/:trade_request_id', to: 'trade_requests#accept', as: 'trade_request_accept'
  post '/users/:id/decline_trade/:trade_request_id', to: 'trade_requests#decline', as: 'trade_request_decline'
  post '/users/:id', to: 'users#destroy', as: 'delete_user'
  get '/users/:id/trade_requests', to: 'trade_requests#user', as: 'user_trade_requests'
  post '/logout', to: 'sessions#destroy', as: 'logout'
#  get '/users/:id/trade_requests/:pokemon_id'


  # get '/users/:id/pokemons', to: 'users#pokemons'
  # get '/users/:id/pokemons/:pokemon_id', to: 'user_pokemons#show'
  # post '/users/:id/pokemons/:pokemon_id', to: 'user_pokemons#create'
end

app/models/trade_request.rb
class TradeRequest < ApplicationRecord
  belongs_to :give, class_name: 'UserPokemon'
  belongs_to :take, class_name: 'UserPokemon'
  validates_uniqueness_of :give_id, scope: :take_id
  # validate :cannot_make_same_trade_request

# this is a little glitchy, gonna ask jeff what's up
  # def cannot_make_same_trade_request
  #   byebug
  #   if TradeRequest.find_by(give: self.give, take: self.take).present?
  #     errors.add(:give, "can't make same trade request twice")
  #   end
  # end
end

app/controllers/trade_requests_controller.rb
class TradeRequestsController < ApplicationController

  def new
    @take = UserPokemon.find(params[:pokemon_id])
    @possible_gives = User.find(session[:user_id]).user_pokemons
  end

  def create
    give = UserPokemon.find(params[:give_id])
    take = UserPokemon.find(params[:take_id])
    trade_request = TradeRequest.create(give: give, take: take)
    # if trade_request.save
      flash[:message] = "You have requested to trade  #{trade_request.give.nickname} in exchange for #{trade_request.take.user.name}'s #{trade_request.take.pokemon.name}."
    # else
    #   flash[:message] = "You have already made this trade request."
    # end
    redirect_to user_path(take.user)
  end

  def show
    @trade_request = TradeRequest.find(params[:id])
  end

  def user
    @user = User.find(session[:user_id])
  end

  def accept
    trade_request = TradeRequest.find(params[:trade_request_id])
    Trader.new(trade_request).execute
    flash[:message] = "Successfully traded #{trade_request.take.nickname} for #{trade_request.take.user.name}'s #{trade_request.give.pokemon.name}!" #this is glitched
    TradeRequest.where('give_id = ? OR take_id = ?', trade_request.give.id, trade_request.give.id).destroy_all
    TradeRequest.where('give_id = ? OR take_id = ?', trade_request.take.id, trade_request.take.id).destroy_all
    redirect_to user_path(session[:user_id])
  end

  def destroy
    trade_request = TradeRequest.find(params[:id])
    trade_request.destroy
    if session[:user_id] == trade_request.give.user.id
      flash[:message] = "Declined your trade request to #{trade_request.take.user.name}."
    else
      flash[:message] = "Declined #{trade_request.give.user.name}'s trade request."
    end
    redirect_to user_path(session[:user_id])
  end

end

app/views/trade_requests/new.html.erb
<h1> You requested to trade for <%= "#{@take.user.name}'s #{@take.pokemon.name}"%>!</h1>

<p><%= label_tag "pokemon", "Choose a Pokemon to Exchange" %></p>
<% @possible_gives.each do |give| %>
<br><strong><%= give.nickname %></strong>
Level <%= give.level %></br>
<p><%= link_to "Initiate trade request", trade_requests_create_path(session[:user_id], give, @take), method: :post %></p>
<% end %>

app/views/trade_requests/user.html.erb
<h2> As Sender: </h2>
<% @user.trade_requests_as_sender.each do |trade_request| %>
 <h6> <%= "You offered to trade your level #{trade_request.give.level} #{trade_request.give.pokemon.name} for #{trade_request.take.user.name}'s level #{trade_request.take.level} #{trade_request.take.pokemon.name}." %>
 <%= link_to "Cancel", trade_request_path(trade_request, trade_request.give.user), method: 'delete'%>
<% end %>

<h2> As Recipient: </h2>
<% @user.trade_requests_as_recipient.each do |trade_request| %>
 <h6> <%= "#{trade_request.give.user.name} wants to trade a level #{trade_request.give.level} #{trade_request.give.pokemon.name} for your level #{trade_request.take.level} #{trade_request.take.pokemon.name}." %>
 <%= link_to "Accept", trade_request_accept_path(@user, trade_request) %> <%= link_to "Decline", trade_request_path(trade_request), method: 'delete'%>
<% end %>